---

- hosts: all
  become: true
  tasks:

  - name: install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: install apache2 package
    tags: apache,apache2,ubuntu
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: change email address in file for admin
    tags: apache,ubuntu,apache2
    lineinfile:
      path: /home/p3xco96/Documents/skusla.txt
      regexp: '^skusla'
      line: Server admin somebody@awesome.net
    when: ansible_distribution == "Ubuntu"
    register: apache2


- hosts: all
  become: true
  tasks:

  - name: create user simone
    tags: always
    user:
      name: simone
      groups: root

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIESDqkMV9DNTpI/mTV7Y/mZ8Hp0FUkEqJOLSqo9AvaCF ansible"


  - name: add sudoers file for simone
    tags: always
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440
