 - name: install apache2 package (Ubuntu)
   tags: apache,apache2,ubuntu
   package:
     name:
       - "{{apache_package_name}}"
       - "{{php_package_name}}"
     state: latest
   when: ansible_distribution == "Ubuntu"
